# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   组织部分
#
#   - 本部分定义了稍后将在配置中引用的不同组织身份。
#
################################################################################
Organizations:
    - &Org4
        # DefaultOrg 定义了 fabric.git 开发环境中使用的组织
        Name: Org4MSP

        # 用于加载 MSP 定义的 ID
        ID: Org4MSP

        MSPDir: ../organizations/peerOrganizations/org4.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org4MSP.admin', 'Org4MSP.peer', 'Org4MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org4MSP.admin', 'Org4MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org4MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org4MSP.peer')"
